# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('contact_email', seahub.base.fields.LowerCaseCharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
