# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_externaldepartment_socialauthuser_usermonitoredrepos_and_more'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachment',
            name='group_message',
        ),
        migrations.RemoveField(
            model_name='messagereply',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='PublicGroup',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
        migrations.DeleteModel(
            name='MessageReply',
        ),
    ]
