# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfiles',
            name='o_uuid',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='relatedfiles',
            name='r_uuid',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
