# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 06:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180326_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='repo_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
