# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180428_0619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupWiki',
        ),
        migrations.DeleteModel(
            name='PersonalWiki',
        ),
    ]
