# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', seahub.base.fields.LowerCaseCharField(max_length=255)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.fileuuidmap')),
            ],
            options={
                'unique_together': {('uuid', 'username')},
            },
        ),
    ]
