# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', seahub.base.fields.LowerCaseCharField(max_length=255)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.FileUUIDMap')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fileparticipant',
            unique_together=set([('uuid', 'username')]),
        ),
    ]
