# Generated by Django 4.2.2 on 2023-06-13 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyOfficeDocKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_key', models.CharField(db_index=True, max_length=36)),
                ('username', models.CharField(max_length=255)),
                ('repo_id', models.CharField(max_length=36)),
                ('file_path', models.TextField()),
                ('repo_id_file_path_md5', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
