# Generated by Django 4.2.16 on 2025-03-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoExtraConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('config_type', models.CharField(max_length=50)),
                ('config_details', models.TextField()),
            ],
            options={
                'db_table': 'repo_extra_config',
                'unique_together': {('repo_id', 'config_type')},
            },
        ),
    ]
