import isHotkey from 'is-hotkey';

export const isModS = isHotkey('mod+s');
export const isModZ = isHotkey('mod+z');
export const isModL = isHotkey('mod+l');
export const isModF = isHotkey('mod+f');
export const isModP = isHotkey('mod+p');
export const isModG = isHotkey('mod+g');
export const isModDot = isHotkey('mod+.');
export const isModComma = isHotkey('mod+,');
export const isModSlash = isHotkey('mod+/');
export const isModBackslash = isHotkey('mod+\'');
export const isModSemicolon = isHotkey('mod+;');
export const isModUp = isHotkey('mod+up');
export const isModDown = isHotkey('mod+down');
export const isModLeft = isHotkey('mod+left');
export const isModRight = isHotkey('mod+right');
export const isModShiftZ = isHotkey('mod+shift+z');
export const isModShiftG = isHotkey('mod+shift+g');
export const isModShiftDot = isHotkey('mod+shift+.');
export const isModShiftComma = isHotkey('mod+shift+,');
export const isShiftEnter = isHotkey('shift+enter');
export const isShiftModEnter = isHotkey('shift+mod+enter');
export const isOptPageUp = isHotkey('opt+pageup');
export const isOptPageDown = isHotkey('opt+pagedown');
export const isSpace = isHotkey('space');
export const isEnter = isHotkey('enter');
