ALTER TABLE "EMAILUSER" ADD COLUMN IF NOT EXISTS "IS_DEPARTMENT_OWNER" INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS "EMAILUSER_IS_ACTIVE" ON "EMAILUSER"("IS_ACTIVE");
CREATE INDEX IF NOT EXISTS "EMAILUSER_IS_DEPARTMENT_OWNER" ON "EMAILUSER"("IS_DEPARTMENT_OWNER");


CREATE TABLE IF NOT EXISTS "REPO_EXTRA_CONFIG" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"REPO_ID" VARCHAR(36) NOT NULL,"CONFIG_TYPE" VARCHAR(50) NOT NULL,"CONFIG_DETAILS" TEXT DEFAULT NULL,UNIQUE ("REPO_ID", "CONFIG_TYPE"));
CREATE INDEX IF NOT EXISTS "IX_REPO_EXTRA_REPO_ID" ON "REPO_EXTRA_CONFIG" ("REPO_ID");
CREATE TABLE IF NOT EXISTS "REPOTRANSFER" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"REPO_ID" VARCHAR(36) NOT NULL,"ORG_ID" INTEGER NOT NULL,"FROM_USER" VARCHAR(255) NOT NULL,"TO" VARCHAR(255) NOT NULL,"TIMESTAMP" DATETIME NOT NULL,"OPERATOR" VARCHAR(255) NOT NULL);
CREATE INDEX IF NOT EXISTS "IDX_FILE_TRANSFER_ORG_ID" ON "REPOTRANSFER" ("ORG_ID");
CREATE INDEX IF NOT EXISTS "IDX_FILE_TRANSFER_TIMESTAMP" ON "REPOTRANSFER" ("TIMESTAMP");
CREATE TABLE IF NOT EXISTS "GROUP_INVITE_LINK" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"TOKEN" VARCHAR(40) NOT NULL,"GROUP_ID" INTEGER NOT NULL,"CREATED_AT" DATETIME NOT NULL,"CREATED_BY" VARCHAR(255) NOT NULL);
CREATE INDEX IF NOT EXISTS "GROUP_INVITE_LINK_GROUP_ID" ON "GROUP_INVITE_LINK" ("GROUP_ID");
CREATE INDEX IF NOT EXISTS "GROUP_INVITE_LINK_TOKEN" ON "GROUP_INVITE_LINK" ("TOKEN");
CREATE TABLE IF NOT EXISTS "ORG_LAST_ACTIVE_TIME" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"ORG_ID" INTEGER NOT NULL,"TIMESTAMP" DATETIME NOT NULL,UNIQUE ("ORG_ID"));
CREATE INDEX IF NOT EXISTS "IX_ORG_LAST_ACTIVE_TIME_ORG_ID" ON "ORG_LAST_ACTIVE_TIME" ("ORG_ID");
CREATE TABLE IF NOT EXISTS "GROUP_MEMBER_AUDIT" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"ORG_ID" INTEGER NOT NULL,"OPERATOR" VARCHAR(255) NOT NULL,"USER" VARCHAR(255) NOT NULL,"GROUP_ID" INTEGER NOT NULL,"OPERATION" VARCHAR(128) NOT NULL,"TIMESTAMP" DATETIME NOT NULL);
CREATE INDEX IF NOT EXISTS "IDX_GROUP_MEMBER_AUDIT_ORG_ID" ON "GROUP_MEMBER_AUDIT" ("ORG_ID");
CREATE INDEX IF NOT EXISTS "IDX_GROUP_MEMBER_AUDIT_TIMESTAMP" ON "GROUP_MEMBER_AUDIT" ("TIMESTAMP");
CREATE INDEX IF NOT EXISTS "IDX_GROUP_MEMBER_AUDIT_OPERATOR" ON "GROUP_MEMBER_AUDIT" ("OPERATOR");
CREATE INDEX IF NOT EXISTS "IDX_GROUP_MEMBER_AUDIT_USER" ON "GROUP_MEMBER_AUDIT" ("USER");
CREATE INDEX IF NOT EXISTS "IDX_GROUP_MEMBER_AUDIT_GROUP_ID" ON "GROUP_MEMBER_AUDIT" ("GROUP_ID");
CREATE TABLE IF NOT EXISTS "NOTIFICATIONS_SYSUSERNOTIFICATION" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"MESSAGE" TEXT NOT NULL,"TO_USER" VARCHAR(255) NOT NULL,"SEEN" TINYINT NOT NULL,"CREATED_AT" DATETIME NOT NULL);
CREATE INDEX IF NOT EXISTS "NOTIFICATIONS_SYSUSERNOTIFICATION_TO_USER_E0C9101E" ON "NOTIFICATIONS_SYSUSERNOTIFICATION" ("TO_USER");
CREATE INDEX IF NOT EXISTS "NOTIFICATIONS_SYSUSERNOTIFICATION_SEEN_9D851BF7" ON "NOTIFICATIONS_SYSUSERNOTIFICATION" ("SEEN");
CREATE INDEX IF NOT EXISTS "NOTIFICATIONS_SYSUSERNOTIFICATION_CREATED_AT_56FFD2A0" ON "NOTIFICATIONS_SYSUSERNOTIFICATION" ("CREATED_AT");
CREATE TABLE IF NOT EXISTS "STATS_AI_BY_TEAM" ("ID" BIGINT PRIMARY KEY AUTO_INCREMENT,"ORG_ID" BIGINT NOT NULL,"MONTH" DATE NOT NULL,"MODEL" VARCHAR(100) NOT NULL,"INPUT_TOKENS" INTEGER DEFAULT NULL,"OUTPUT_TOKENS" INTEGER DEFAULT NULL,"COST" DOUBLE NOT NULL,"CREATED_AT" DATETIME DEFAULT NULL,"UPDATED_AT" DATETIME DEFAULT NULL,UNIQUE ("ORG_ID", "MONTH", "MODEL"));
CREATE INDEX IF NOT EXISTS "IX_STATS_AI_BY_TEAM_ORG_ID_MONTH" ON "STATS_AI_BY_TEAM" ("ORG_ID", "MONTH");
CREATE TABLE IF NOT EXISTS "STATS_AI_BY_OWNER" ("ID" BIGINT PRIMARY KEY AUTO_INCREMENT,"USERNAME" VARCHAR(255) NOT NULL,"MONTH" DATE NOT NULL,"MODEL" VARCHAR(100) NOT NULL,"INPUT_TOKENS" INTEGER DEFAULT NULL,"OUTPUT_TOKENS" INTEGER DEFAULT NULL,"COST" DOUBLE NOT NULL,"CREATED_AT" DATETIME DEFAULT NULL,"UPDATED_AT" DATETIME DEFAULT NULL,UNIQUE ("USERNAME", "MONTH", "MODEL"));
CREATE INDEX IF NOT EXISTS "IX_STATS_AI_BY_OWNER_USERNAME_MONTH" ON "STATS_AI_BY_OWNER" ("USERNAME", "MONTH");


CREATE INDEX IF NOT EXISTS "IDX_USER_SEEN" on "SDOC_NOTIFICATION" ("USERNAME", "SEEN");

ALTER TABLE "ORGANIZATIONS_ORGSETTINGS" ADD COLUMN IF NOT EXISTS "IS_ACTIVE" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "REPO_METADATA" ADD COLUMN IF NOT EXISTS "TAGS_ENABLED" INTEGER NULL;
ALTER TABLE "REPO_METADATA" ADD COLUMN IF NOT EXISTS "TAGS_LANG" VARCHAR(36) NULL;
ALTER TABLE "REPO_METADATA" ADD COLUMN IF NOT EXISTS "DETAILS_SETTINGS" TEXT NULL;
ALTER TABLE "REPO_METADATA" ADD COLUMN IF NOT EXISTS "OCR_ENABLED" INTEGER NULL;
ALTER TABLE "REPO_METADATA" ADD COLUMN IF NOT EXISTS "GLOBAL_HIDDEN_COLUMNS" TEXT DEFAULT NULL;
CREATE INDEX IF NOT EXISTS "KEY_LAST_FACE_CLUSTER_TIME_FACE_RECOGNITION_ENABLED" ON  "REPO_METADATA" ("FACE_RECOGNITION_ENABLED", "LAST_FACE_CLUSTER_TIME");



CREATE TABLE IF NOT EXISTS "USER_QUOTA_USAGE" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"USERNAME" VARCHAR(255) NOT NULL,"ORG_ID" INTEGER NOT NULL,"QUOTA" BIGINT DEFAULT NULL,"USAGE" BIGINT DEFAULT NULL,"TIMESTAMP" DATETIME NOT NULL,UNIQUE ("USERNAME"));
CREATE INDEX IF NOT EXISTS "IDX_USER_QUOTA_USAGE_TIMESTAMP" ON "USER_QUOTA_USAGE" ("TIMESTAMP");
CREATE INDEX IF NOT EXISTS "IDX_USER_QUOTA_USAGE_ORG_ID" ON "USER_QUOTA_USAGE" ("ORG_ID");
CREATE TABLE IF NOT EXISTS "ORG_QUOTA_USAGE" ("ID" INTEGER PRIMARY KEY AUTO_INCREMENT,"ORG_ID" INTEGER NOT NULL,"QUOTA" BIGINT DEFAULT NULL,"USAGE" BIGINT DEFAULT NULL,"TIMESTAMP" DATETIME NOT NULL,UNIQUE ("ORG_ID"));
CREATE INDEX IF NOT EXISTS "IDX_ORG_QUOTA_USAGE_TIMESTAMP" ON "ORG_QUOTA_USAGE" ("TIMESTAMP");
