# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='constance_key', max_length=255, unique=True)),
                ('value', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'constance',
                'verbose_name_plural': 'constances',
                'db_table': 'constance_config',
            },
        ),
    ]
