pipeline:
  build:
    image: docker.seafile.top/drone/seafile-pro-builder:v4
    pull: true
    secrets: [ github_token, npm_token, travis ]
    when:
      branch:
        event: [ push, pull_request ]
        include: [ master, python3-master ]
        exclude: []

    commands:
      - .travis/test_seahub_changes.sh; rc=$?; if test "$rc" -eq 0; then ./tests/seahubtests.sh init && ./tests/seahubtests.sh runserver && ./tests/seahubtests.sh test; else true; fi
      - echo "hello"
