pipeline:
  build:
    image: docker.seafile.top/drone/seafile-pro-builder:v4
    pull: true
    secrets: [ github_token, npm_token, travis ]
    when:
      branch:
        event: [ push, pull_request ]

    commands:
      - cd /tmp/seafile-test-deploy && git fetch origin python3:python3 && git checkout python3
      - ./bootstrap.sh && cd -
      - export CCNET_CONF_DIR=/tmp/ccnet SEAFILE_CONF_DIR=/tmp/seafile-data
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - cd /drone/src/github.com/haiwen/seahub
      - ./tests/install-deps.sh
      - pip install -r test-requirements.txt
      - if .travis/test_seahub_changes.sh; then ./tests/seahubtests.sh init && ./tests/seahubtests.sh runserver && ./tests/seahubtests.sh test; else true; fi
      - if test $DRONE_COMMIT_BRANCH = "master"; then .travis/dist_and_push.sh; else true; fi
