# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 08:33


from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('department', models.CharField(max_length=512)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('intro', models.TextField(blank=True, max_length=256)),
                ('lang_code', models.TextField(blank=True, max_length=50, null=True)),
                ('login_id', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('contact_email', models.EmailField(blank=True, db_index=True, max_length=225, null=True)),
                ('institution', models.CharField(blank=True, db_index=True, default=b'', max_length=225, null=True)),
                ('list_in_address_book', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
