# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20190122_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, db_index=True, default='', max_length=225, null=True),
        ),
    ]
