# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20190122_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ocm_server',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocm_user',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, db_index=True, default='', max_length=225, null=True),
        ),
    ]
