import seahub.settings as settings

ENABLE_THIRDPARTY_EDITOR = getattr(settings, 'ENABLE_THIRDPARTY_EDITOR', False)
THIRDPARTY_EDITOR_ACTION_URL_DICT = getattr(settings, 'THIRDPARTY_EDITOR_ACTION_URL_DICT', {})
THIRDPARTY_EDITOR_ACCESS_TOKEN_EXPIRATION = getattr(settings, 'THIRDPARTY_EDITOR_ACCESS_TOKEN_EXPIRATION', 12 * 60 * 60)
