# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255)),
                ('ticket', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyGrantingTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('pgtiou', models.CharField(blank=True, max_length=255, null=True)),
                ('pgt', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('session_key', 'user')},
            },
        ),
    ]
