# Generated by Django 4.2.16 on 2025-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_type',
            field=models.CharField(choices=[('guest', 'guest'), ('default', 'default'), ('Organization', 'org')], default='guest', max_length=20),
        ),
    ]
