# Generated by Django 4.2.2 on 2024-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_reposhareinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_type',
            field=models.CharField(choices=[('guest', 'guest'), ('default', 'default')], default='guest', max_length=20),
        ),
    ]
