# Generated by Django 4.2.2 on 2024-08-27 14:16

import datetime
from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('primary', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('msg_type', models.CharField(db_index=True, max_length=30)),
                ('detail', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('seen', models.BooleanField(default=False, verbose_name='seen')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
