# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 07:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
