# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181115_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='seen'),
        ),
    ]
