# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
