# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('option_key', models.CharField(db_index=True, max_length=50)),
                ('option_val', models.CharField(max_length=50)),
            ],
        ),
    ]
