# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 08:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroptions',
            name='option_key',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
