# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 09:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoSecretKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('secret_key', models.CharField(max_length=44)),
            ],
        ),
    ]
