# Generated by Django 4.2.16 on 2025-03-24 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgLastActivityTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'org_last_active_time',
            },
        ),
        migrations.CreateModel(
            name='RepoTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=36)),
                ('org_id', models.IntegerField(db_index=True)),
                ('from_user', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'RepoTransfer',
            },
        ),
    ]
