# Generated by Django 4.2.16 on 2025-06-03 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_orglastactivitytime_repotransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True)),
                ('group_id', models.IntegerField(db_index=True)),
                ('user', models.EmailField(db_index=True, max_length=254)),
                ('operator', models.CharField(db_index=True, max_length=255)),
                ('operation', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'group_member_audit',
            },
        ),
        migrations.CreateModel(
            name='OrgQuotaUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True, unique=True)),
                ('quota', models.BigIntegerField()),
                ('usage', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'org_quota_usage',
            },
        ),
        migrations.CreateModel(
            name='UserQuotaUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('org_id', models.IntegerField(db_index=True)),
                ('quota', models.BigIntegerField()),
                ('usage', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'user_quota_usage',
            },
        ),
    ]
