# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 12:42


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reposecretkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecomment',
            name='detail',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
