# Generated by Django 4.2.16 on 2025-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_groupmemberaudit_orgquotausage_userquotausage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('obj_type', models.CharField(max_length=128)),
                ('obj_id', models.CharField(max_length=40)),
                ('obj_name', models.CharField(max_length=255)),
                ('delete_time', models.DateTimeField()),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('commit_id', models.CharField(max_length=40)),
                ('path', models.TextField()),
                ('size', models.BigIntegerField()),
            ],
            options={
                'db_table': 'FileTrash',
                'ordering': ['-delete_time'],
            },
        ),
    ]
