# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181016_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('outer_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'external_department',
                'unique_together': {('provider', 'outer_id')},
            },
        ),
        migrations.CreateModel(
            name='SocialAuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('provider', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=255)),
                ('extra_data', models.TextField()),
            ],
            options={
                'db_table': 'social_auth_usersocialauth',
                'unique_together': {('provider', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='UserMonitoredRepos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('email', 'repo_id')},
            },
        ),
        migrations.RemoveField(
            model_name='filediscuss',
            name='group_message',
        ),
        migrations.DeleteModel(
            name='GroupEnabledModule',
        ),
        migrations.RemoveField(
            model_name='innerpubmsgreply',
            name='reply_to',
        ),
        migrations.DeleteModel(
            name='UserEnabledModule',
        ),
        migrations.AlterField(
            model_name='filecomment',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='FileDiscuss',
        ),
        migrations.DeleteModel(
            name='InnerPubMsg',
        ),
        migrations.DeleteModel(
            name='InnerPubMsgReply',
        ),
    ]
