# Generated by Django 4.2.9 on 2024-03-30 08:54

from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_externaldepartment_socialauthuser_usermonitoredrepos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSSOToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('username', seahub.base.fields.LowerCaseCharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('success', 'success'), ('error', 'error')], default='waiting', max_length=10)),
                ('api_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accessed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='socialauthuser',
            name='extra_data',
            field=models.TextField(null=True),
        ),
    ]
