# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('username', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('origin_repo_id', models.CharField(max_length=36)),
                ('origin_file_version', models.CharField(max_length=100)),
                ('draft_repo_id', models.CharField(max_length=36)),
                ('draft_file_path', models.CharField(max_length=2048)),
                ('origin_file_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.FileUUIDMap')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([('username', 'draft_repo_id')]),
        ),
    ]
