# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('username', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('status', models.CharField(default='open', max_length=20)),
                ('draft_file_path', models.CharField(max_length=1024)),
                ('origin_repo_id', models.CharField(db_index=True, max_length=36)),
                ('origin_file_uuid', models.UUIDField(unique=True)),
                ('origin_file_version', models.CharField(max_length=100)),
                ('publish_file_version', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.draft')),
            ],
        ),
    ]
