# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftreview',
            name='draft_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drafts.Draft'),
        ),
    ]
