# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-15 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='draft',
            unique_together=set([]),
        ),
    ]
