# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_auto_20181011_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('comment', models.TextField()),
                ('detail', models.TextField()),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftReview')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
