# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 06:48


from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_draftreview_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='draftreview',
            name='draft_id',
        ),
        migrations.RemoveField(
            model_name='draftreview',
            name='origin_file_uuid',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review_id',
        ),
        migrations.RemoveField(
            model_name='reviewreviewer',
            name='review_id',
        ),
        migrations.AddField(
            model_name='draft',
            name='publish_file_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='draft',
            name='origin_file_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='DraftReview',
        ),
        migrations.DeleteModel(
            name='ReviewComment',
        ),
        migrations.DeleteModel(
            name='ReviewReviewer',
        ),
        migrations.AddField(
            model_name='draftreviewer',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.Draft'),
        ),
    ]
