# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_auto_20180915_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('creator', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('draft_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drafts.Draft')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
