# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('drafts', '0003_reviewcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftreview',
            name='origin_file_path',
        ),
        migrations.AddField(
            model_name='draftreview',
            name='origin_file_uuid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tags.FileUUIDMap'),
            preserve_default=False,
        ),
    ]
