# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-10 06:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_auto_20190301_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='origin_file_uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='origin_repo_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
