# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_reviewcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reviewer', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafts.DraftReview')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
