# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0003_draftreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftreview',
            name='publish_file_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
