# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0004_reviewreviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewreviewer',
            options={},
        ),
        migrations.RemoveField(
            model_name='reviewreviewer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviewreviewer',
            name='updated_at',
        ),
    ]
