# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-05 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.TextField(blank=True, null=True)),
                ('repo_id', models.CharField(max_length=36)),
                ('repo_name', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('abuse_type', models.CharField(choices=[(b'copyright', b'copyright'), (b'virus', b'virus'), (b'abuse_content', b'abuse_content'), (b'other', b'other')], db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('handled', models.BooleanField(db_index=True, default=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
