# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.TextField(blank=True, null=True)),
                ('repo_id', models.CharField(max_length=36)),
                ('repo_name', models.CharField(max_length=255)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('abuse_type', models.CharField(choices=[('copyright', 'copyright'), ('virus', 'virus'), ('abuse_content', 'abuse_content'), ('other', 'other')], db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('handled', models.BooleanField(db_index=True, default=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
