export default OperationTypes = {
  DELETE_ROW: 'DELETE_NODE',
  INSERT_ROW: 'INSERT_ROW',
  DELETE_COLUMN: 'DELETE_COLUMN',
  INSERT_COLUMN: 'INSERT_COLUMN',
  MODIFY_CELL: 'MODIFY_CELL',
  MODIFY_COLUMN: 'MODIFY_COLUMN',
}
