# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsandconditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='date_active',
            field=models.DateTimeField(blank=True, help_text='Leave Null To Never Make Active', null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='info',
            field=models.TextField(blank=True, help_text="Provide users with some info about what's changed and why", null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='slug',
            field=models.SlugField(default='site-terms'),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='date_accepted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Accepted'),
        ),
        migrations.AlterField(
            model_name='usertermsandconditions',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
