# Generated by Django 2.2.14 on 2021-09-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocm_via_webdav', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareReceived',
            new_name='ReceivedShares',
        ),
    ]
