# Generated by Django 2.2.14 on 2021-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocm_via_webdav', '0002_auto_20210926_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedshares',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receivedshares',
            name='permissions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='receivedshares',
            name='protocol_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='receivedshares',
            table='ocm_via_webdav_received_shares',
        ),
    ]
