# Generated by Django 2.2.14 on 2021-09-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocm_via_webdav', '0003_auto_20210926_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedshares',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
    ]
