# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-07-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoFilesAutoDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'repo_files_auto_del',
            },
        ),
    ]
