import { CellType } from './column';

const MAX_GROUP_LEVEL = 3;

const GROUP_DATE_GRANULARITY = {
  DAY: 'day',
  WEEK: 'week',
  MONTH: 'month',
  QUARTAR: 'quartar',
  YEAR: 'year',
};

const DISPLAY_GROUP_DATE_GRANULARITY = {
  [GROUP_DATE_GRANULARITY.DAY]: 'By_day',
  [GROUP_DATE_GRANULARITY.WEEK]: 'By_week',
  [GROUP_DATE_GRANULARITY.MONTH]: 'By_month',
  [GROUP_DATE_GRANULARITY.QUARTAR]: 'By_quarter',
  [GROUP_DATE_GRANULARITY.YEAR]: 'By_year',
};

const GROUP_GEOLOCATION_GRANULARITY = {
  PROVINCE: 'province',
  CITY: 'city',
  DISTRICT: 'district',
  COUNTRY: 'country',
};

const DISPLAY_GROUP_GEOLOCATION_GRANULARITY = {
  [GROUP_GEOLOCATION_GRANULARITY.PROVINCE]: 'By_province',
  [GROUP_GEOLOCATION_GRANULARITY.CITY]: 'By_city',
  [GROUP_GEOLOCATION_GRANULARITY.DISTRICT]: 'By_district',
};

const SUPPORT_GROUP_COLUMN_TYPES = [
  CellType.TEXT,
  CellType.CTIME,
  CellType.MTIME,
  CellType.CREATOR,
  CellType.LAST_MODIFIER,
];

const GROUPBY_DATE_GRANULARITY_LIST = [
  GROUP_DATE_GRANULARITY.DAY,
  GROUP_DATE_GRANULARITY.WEEK,
  GROUP_DATE_GRANULARITY.MONTH,
  GROUP_DATE_GRANULARITY.QUARTAR,
  GROUP_DATE_GRANULARITY.YEAR,
];

export {
  MAX_GROUP_LEVEL,
  GROUP_DATE_GRANULARITY,
  DISPLAY_GROUP_DATE_GRANULARITY,
  GROUP_GEOLOCATION_GRANULARITY,
  DISPLAY_GROUP_GEOLOCATION_GRANULARITY,
  SUPPORT_GROUP_COLUMN_TYPES,
  GROUPBY_DATE_GRANULARITY_LIST,
};
