# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0005_auto_20180615_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Communicate',
        ),
    ]
