# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-27 02:41


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMemberQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True)),
                ('quota', models.IntegerField()),
            ],
        ),
    ]
