# Generated by Django 4.2.16 on 2025-01-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
