# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-16 03:23


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_orgsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='org_id',
            field=models.IntegerField(unique=True),
        ),
    ]
