# Generated by Django 5.2.6 on 2026-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_orgsettings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='monthly_traffic_limit',
            field=models.BigIntegerField(default=0),
        ),
    ]
