# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190116_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSAMLConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(unique=True)),
                ('metadata_url', models.TextField()),
                ('domain', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'org_saml_config',
            },
        ),
        migrations.CreateModel(
            name='OrgAdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField(db_index=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('org_id', 'key')},
            },
        ),
    ]
