# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-24 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', seahub.base.fields.LowerCaseCharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.AlterUniqueTogether(
            name='workspaces',
            unique_together=set([('owner', 'repo_id')]),
        ),
    ]
