# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupShareWorkspace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(db_index=True, max_length=255)),
                ('group_id', models.IntegerField(db_index=True)),
                ('permission', models.CharField(max_length=15)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtable.Workspaces')),
            ],
            options={
                'db_table': 'group_share_workspace',
            },
        ),
        migrations.CreateModel(
            name='UserShareWorkspace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(db_index=True, max_length=255)),
                ('to_user', models.CharField(db_index=True, max_length=255)),
                ('permission', models.CharField(max_length=15)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtable.Workspaces')),
            ],
            options={
                'db_table': 'user_share_workspace',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usershareworkspace',
            unique_together=set([('workspace', 'to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='groupshareworkspace',
            unique_together=set([('workspace', 'group_id')]),
        ),
    ]
