# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-26 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(db_index=True, max_length=255)),
                ('to_user', models.CharField(db_index=True, max_length=255)),
                ('permission', models.CharField(max_length=15)),
                ('dtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtable.DTables')),
            ],
            options={
                'db_table': 'share_dtable',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sharedtable',
            unique_together=set([('dtable', 'to_user')]),
        ),
    ]
