# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-02 05:20


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTableShare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(db_index=True, max_length=255)),
                ('to_user', models.CharField(db_index=True, max_length=255)),
                ('permission', models.CharField(max_length=15)),
                ('dtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtable.DTables')),
            ],
            options={
                'db_table': 'dtable_share',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dtableshare',
            unique_together={('dtable', 'to_user')},
        ),
    ]
