# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-21 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaces',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workspaces',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workspaces',
            name='owner',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workspaces',
            name='repo_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='workspaces',
            unique_together=set([]),
        ),
    ]
