# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0002_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTableApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=40, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(max_length=255)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('permission', models.CharField(max_length=15)),
                ('dtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dtable.DTables')),
            ],
            options={
                'db_table': 'dtable_api_token',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dtableapitoken',
            unique_together=set([('dtable', 'app_name')]),
        ),
    ]
