# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dtable', '0003_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDTableLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('ctime', models.DateTimeField(default=datetime.datetime.now)),
                ('password', models.CharField(max_length=128, null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('permission', models.CharField(choices=[('read-only', 'read only'), ('read-write', 'read and write')], db_index=True, default='read-only', max_length=50)),
                ('dtable', models.ForeignKey(db_column='dtable_id', on_delete=django.db.models.deletion.CASCADE, to='dtable.DTables')),
            ],
            options={
                'db_table': 'dtable_share_links',
            },
        ),
    ]
