# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 07:10


from django.db import migrations
import seahub.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institutionquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionadmin',
            name='user',
            field=seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255),
        ),
    ]
