import { gettext } from './utils/constants';

gettext('You have not shared any folders');
gettext('You don\'t have any share links');
gettext('You don\'t have any upload links');
gettext('You don\'t have any favorite items yet');
gettext('Modify');
gettext('Import Users');
gettext('No connected devices');
gettext('No sync errors');
gettext('No groups');
gettext('No notifications');
gettext('Notification Detail');
gettext('No share links');
gettext('No upload links');
gettext('No invitations');
gettext('No terms and conditions');
gettext('Tip: libraries deleted {trashReposExpireDays} days ago will be cleaned automatically.');
gettext('No favorites');
gettext('No folders shared');
gettext('No Admin login logs');
gettext('No Admin operation logs');
gettext('No permission logs');
gettext('No login logs');
gettext('No file update logs');
gettext('No file access logs');
gettext('Save Selected Items');
