# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 07:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('repo_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uuid', to='tags.FileUUIDMap')),
                ('parent_folder_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder_uuid', to='tags.FileUUIDMap')),
                ('repo_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_tags.RepoTags')),
            ],
        ),
    ]
