# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_tags', '0002_remove_filetags_parent_folder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetags',
            name='file_uuid',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
