# Generated by Django 5.2.6 on 2026-01-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uploadlinkshare',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
