# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSharePermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('permission', models.TextField()),
            ],
            options={
                'db_table': 'custom_share_permission',
            },
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='permission',
            field=models.CharField(choices=[('view_download', 'Preview only and can download'), ('view_only', 'Preview only and disable download'), ('edit_download', 'Edit and can download'), ('edit_only', 'Edit and disable download'), ('view_download_upload', 'Preview only and can download and upload')], db_index=True, default='view_download', max_length=50),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='s_type',
            field=models.CharField(db_index=True, default='f', max_length=2),
        ),
        migrations.AlterField(
            model_name='privatefiledirshare',
            name='s_type',
            field=models.CharField(default='f', max_length=5),
        ),
    ]
