# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models
import django.db.models.deletion
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('path', models.TextField(default='/')),
                ('revision_id', models.CharField(db_index=True, max_length=255)),
                ('username', seahub.base.fields.LowerCaseCharField(db_index=True, max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revision_tag.tags')),
            ],
        ),
    ]
