# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiontags',
            name='path',
            field=models.TextField(default='/'),
        ),
    ]
