# Generated by Django 4.2.16 on 2025-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WPSFileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=36)),
                ('path', models.CharField(max_length=512)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'wps_file_version',
                'indexes': [models.Index(fields=['repo_id', 'path'], name='wps_file_ve_repo_id_f8958f_idx')],
                'unique_together': {('repo_id', 'path')},
            },
        ),
    ]
