# Generated by Django 4.2.13 on 2024-07-15 06:58

from django.db import migrations, models
import django.utils.timezone
import seahub.base.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', seahub.base.fields.LowerCaseCharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wiki_wiki2',
                'ordering': ['name'],
                'unique_together': {('owner', 'repo_id')},
            },
        ),
    ]
