# Generated by Django 4.2.2 on 2024-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPageTrash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(db_index=True, max_length=36)),
                ('doc_uuid', models.TextField()),
                ('page_id', models.CharField(max_length=4)),
                ('parent_page_id', models.CharField(max_length=4)),
                ('subpages', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('delete_time', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField()),
            ],
            options={
                'db_table': 'WikiPageTrash',
            },
        ),
    ]
