# Generated by Django 5.2.6 on 2026-03-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki2', '0002_wiki2publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki2Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_id', models.CharField(db_index=True, max_length=36)),
                ('enable_link_repos', models.BooleanField(default=True)),
                ('linked_repos', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'wiki_settings',
            },
        ),
        migrations.AddField(
            model_name='wiki2publish',
            name='enable_server_render',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WikiFileViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_id', models.CharField(db_index=True, max_length=36)),
                ('name', models.CharField(default='Default', max_length=255)),
                ('linked_repo_id', models.CharField(max_length=36)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'wiki_file_views',
                'unique_together': {('wiki_id', 'name')},
            },
        ),
    ]
