name: Seahub Dist CI

on:
  push:
    branches:
      - "alphabox-9.0"

env:
  TOKEN_FOR_PUSH_TO_SEAHUB_PRIV: ${{ secrets.TOKEN_FOR_PUSH_TO_SEAHUB_PRIV }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: gettext for django
        run: sudo apt-get install gettext python3-wheel libjwt-dev

      - name: Build dist branch
        run: |
          cd $GITHUB_WORKSPACE/tests/
          chmod +x alphabox_9.0_dist.sh
          ./alphabox_9.0_dist.sh
